### ISSUE TITLE
Add lookerstudio visualization for all main databases

### ISSUE THREAD

**Issue by rickstaa** [sdr-enthusiasts/plane-alert-db#115]
### Is your feature request related to a problem? Please describe.

Currently, https://lookerstudio.google.com/u/0/reporting/eb19ab53-b622-4946-b34a-9667232c136d/page/4taCC contains a visualization dashboard for the [plane-alert-db.csv](https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/plane-alert-db.csv) database. Looks like the dashboard was added in https://github.com/sdr-enthusiasts/plane-alert-db/commit/a0c3dd86929023c74ecd8c1a2ecb3f7e26c1a8f8 by @Sportsbadger.

### Describe the solution you'd like

I think it would be nice also to include such a dashboard for the:

- https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/plane-alert-twitter-blocked-images.csv
- https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/plane-alert-ukraine-images.csv

or include these results in the already existing dashboard by generating a `plane-alert-db-extended.csv` file.

**Comment by Phaeton** [comment]
@rickstaa I made a draft that reproduces the old report the best I could. There is a page for each of the *.csv files. 

###### Source Data
- [plane-alert-db.csv](https://raw.githubusercontent.com/sdr-enthusiasts/plane-alert-db/main/plane-alert-db.csv)
- [twitter-blocked.csv](https://raw.githubusercontent.com/sdr-enthusiasts/plane-alert-db/main/plane-alert-twitter-blocked.csv)
- [ukraine.csv](https://raw.githubusercontent.com/sdr-enthusiasts/plane-alert-db/main/plane-alert-ukraine.csv)

###### Looker Studio Report
[https://lookerstudio.google.com/reporting/fbc584d8-559f-4839-84e7-f581767ec778](https://lookerstudio.google.com/reporting/fbc584d8-559f-4839-84e7-f581767ec778)

Give it a spin and let me know if anything looks odd.

**Comment by rickstaa** [comment]
> @rickstaa I made a draft that reproduces the old report the best I could. There is a page for each of the *.csv files.
> 
> ###### Source Data
> * [plane-alert-db.csv](https://raw.githubusercontent.com/sdr-enthusiasts/plane-alert-db/main/plane-alert-db.csv)
> * [twitter-blocked.csv](https://raw.githubusercontent.com/sdr-enthusiasts/plane-alert-db/main/plane-alert-twitter-blocked.csv)
> * [ukraine.csv](https://raw.githubusercontent.com/sdr-enthusiasts/plane-alert-db/main/plane-alert-ukraine.csv)
> 
> ###### Looker Studio Report
> https://lookerstudio.google.com/reporting/fbc584d8-559f-4839-84e7-f581767ec778
> 
> Give it a spin and let me know if anything looks odd.

Hey @Phaeton great that you are trying to tackle this issue. I checked your dashboard and it looks similar. If you want to have it more similar to @Sportsbadger's dashboard, you can also just copy the dashboard and start from there:

![image](https://user-images.githubusercontent.com/17570430/229350160-588aa0a6-2007-4e3a-a78c-63fc113535a9.png)

How do the Looker studio databases get updated in your current implementation? I checked, and it seems there is no native GitHub integration in Looker Studio. Maybe we can import the databases to google sheets and then use these as inputs to Looker Studio. I think the [IMPORTDATA](https://www.causal.app/formulae/importdata-google-sheets#:~:text=To%20import%20the%20data%2C%20open,that%20you%20want%20to%20import.) function or the [google sheets GitHub action](https://github.com/marketplace/actions/google-spreadsheet-csv-importer) can be used to do this automatically (see https://stackoverflow.com/questions/75495044/read-a-csv-from-github-to-google-sheets).

**Comment by Phaeton** [comment]
> 
> How do the Looker studio databases get updated in your current implementation? I checked, and it seems there is no native GitHub integration in Looker Studio. Maybe we can import the databases to google sheets and then use these as inputs to Looker Studio. I think the [IMPORTDATA](https://stackoverflow.com/questions/75495044/read-a-csv-from-github-to-google-sheets) function or the [google sheets GitHub action](https://github.com/marketplace/actions/google-spreadsheet-csv-importer) can be used to do this automatically (see https://stackoverflow.com/questions/75495044/read-a-csv-from-github-to-google-sheets).

@rickstaa I originally attempted to copy the dashboard, but the datasets it was using were unclear based on their naming. The [Dashboard](https://lookerstudio.google.com/reporting/fbc584d8-559f-4839-84e7-f581767ec778) I built essentially follows your flow above. Data is connected to Github via IMPORTDATA into a Google sheet, one tab for each .csv file. Dashboard links back to the Google Sheet.

You mentioned "more similar". Is there something missing? I tried to include everything to make it as like-for-like as possible.

**Comment by rickstaa** [comment]
> > How do the Looker studio databases get updated in your current implementation? I checked, and it seems there is no native GitHub integration in Looker Studio. Maybe we can import the databases to google sheets and then use these as inputs to Looker Studio. I think the [IMPORTDATA](https://stackoverflow.com/questions/75495044/read-a-csv-from-github-to-google-sheets) function or the [google sheets GitHub action](https://github.com/marketplace/actions/google-spreadsheet-csv-importer) can be used to do this automatically (see https://stackoverflow.com/questions/75495044/read-a-csv-from-github-to-google-sheets).
> 
> @rickstaa I originally attempted to copy the dashboard, but the datasets it was using were unclear based on their naming. The [Dashboard](https://lookerstudio.google.com/reporting/46ff4328-09d3-4e65-ab5a-bd2ba27a18fd) I built essentially follows your flow above. Data is connected to Github via IMPORTDATA into a Google sheet, one tab for each .csv file. Dashboard links back to the Google Sheet.
> 
> You mentioned "more similar". Is there something missing? I tried to include everything to make it as like-for-like as possible.

No, the new dashboard is wonderful. I just noticed some small styling differences, so wondered why you didn't use the COPY feature. Your explanation makes sense and I prefer your styling. Thanks again for implementing this feature! Are the Google sheets public? Love to learn how the `IMPORTDATA` feature works in practice 🤓.
