### ISSUE TITLE
404 

### ISSUE THREAD

**Issue by gourcetools** [sdr-enthusiasts/plane-alert-db#152]
### Describe the bug

404 from clicking twitter list in readme...

### Screenshots / Live demo link
https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/plane-alert-twitter-blocked.txt
![image](https://user-images.githubusercontent.com/120996278/224561175-2c795035-8f00-46bd-bf83-604509ef91c4.png)

**Comment by rickstaa** [comment]
@gourcetools Good catch, thanks! Fixed in d9c9036f77275a867ada72bf61dd93604364e0da.
