### ISSUE TITLE
Change plane_images extension to CSV

### ISSUE THREAD

**Issue by rickstaa** [sdr-enthusiasts/plane-alert-db#155]
### Is your feature request related to a problem? Please describe.

Currently, the file https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/plane_images.txt file is not shown in GitHub's table viewer (see https://github.blog/2013-08-22-see-your-csvs/).

### Describe the solution you'd like

We can fix this by changing the file extension to CSV. @kx1t do you maybe know the reason why the original `planepix.txt` file was in the TXT extension while the rest of the databases were CSV?

### Additional context

We have to fix https://github.com/kx1t/docker-planefence/issues/171 on the upstream before we can do this.

**Comment by dziban303** [comment]
Done I think

**Comment by rickstaa** [comment]
@dziban303 correct this was done in #221.

**Comment by rickstaa** [comment]
The comment about the upstream is related to https://github.com/sdr-enthusiasts/plane-alert-db/issues/156. After https://github.com/kx1t/docker-planefence/issues/171 is fixed, we can remove or shrink the planepix.txt file.
