### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by rickstaa** [sdr-enthusiasts/plane-alert-db#156]
### Is your feature request related to a problem? Please describe.

The repository currently contains the following unused files:

- https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/planepix.txt: Kept because of https://github.com/kx1t/docker-planefence/issues/171.
- https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/scripts/check_james_planes.py: Can be removed if https://github.com/sdr-enthusiasts/plane-alert-db/issues/24 is fixed.
- https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/scripts/create_images_reference.py: Used for creating the new actions but can be removed if we are certain that the actions are correct and desirable.
- https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/scripts/get_unique_bangers_best_items.py: Used for creating the new actions but can be removed if we are certain that the actions are correct and desirable.
- https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/scripts/get_unique_bangers_best_items.py
- https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/scripts/james_planes.py: Can be removed if https://github.com/sdr-enthusiasts/plane-alert-db/issues/24 is fixed.

### Describe the solution you'd like

This action serves as a reminder that these files can be removed in the future.

**Comment by Phaeton** [comment]
@dziban303  @rickstaa  Any reason not to remove the files here: https://github.com/sdr-enthusiasts/plane-alert-db/tree/main/_bin and the old images script here: https://github.com/sdr-enthusiasts/plane-alert-db/blob/main/scripts/create_images_reference.py? Feel like we've been running with the github actions for awhile now and can call it stable.

**Comment by dziban303** [comment]
Seems OK to remove

**Comment by rickstaa** [comment]
@Phaeton, I agree that since we have been running on the new system for months now, we can remove those files. Feel free to remove those files/folders 👍🏻.

**Comment by Phaeton** [comment]
These files are queued to be removed in PR #373
