### ISSUE TITLE
Update Github Action to Add lines to plane_images.txt when new planes added to plane-alert-db.csv

### ISSUE THREAD

**Issue by Phaeton** [sdr-enthusiasts/plane-alert-db#199]
### Is your feature request related to a problem? Please describe.

It would be helpful if the existing Github Action would add  lines to `plane_images.txt` when new planes are added to `plane-alert-db.csv`. It would be beneficial to keep the two files in sync. If the user does not update the `plane_images.txt` file in the pull request that adds a new hex to `plane-alert-db.csv`, a line with the hex followed by 4 commas would be ideal.

**Comment by rickstaa** [comment]
@Phaeton great Idea! I will take a look later this month 💪🏻. If you needed it before, then you can also try it yourself and I will review 👍🏻.
